// Code generated by "stringer -type=Price -linecomment"; DO NOT EDIT.

package foodaccess

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PriceCheap-0]
	_ = x[PriceAffordable-1]
	_ = x[PriceExpensive-2]
}

const _Price_name = "économiqueabordablecher"

var _Price_index = [...]uint8{0, 11, 20, 24}

func (i Price) String() string {
	if i < 0 || i >= Price(len(_Price_index)-1) {
		return "Price(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Price_name[_Price_index[i]:_Price_index[i+1]]
}
