// Code generated by "stringer -type=Category -linecomment"; DO NOT EDIT.

package recipe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CategoryBiscuit-0]
	_ = x[CategoryDessert-1]
	_ = x[CategoryColdDishes-2]
	_ = x[CategoryHotDishes-3]
	_ = x[CategorySideDishes-4]
	_ = x[CategorySauce-5]
}

const _Category_name = "biscuitdessertplat froidplat chaudentréesauce"

var _Category_index = [...]uint8{0, 7, 14, 24, 34, 41, 46}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
