// Code generated by "stringer -type=QuantityUnit -linecomment"; DO NOT EDIT.

package recipe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QuantityUnitMilliliter-0]
	_ = x[QuantityUnitCentiliter-1]
	_ = x[QuantityUnitLiter-2]
	_ = x[QuantityUnitMilligram-3]
	_ = x[QuantityUnitGram-4]
	_ = x[QuantityUnitKilogram-5]
	_ = x[QuantityUnitTeaSpoon-6]
	_ = x[QuantityUnitTableSpoon-7]
	_ = x[QuantityUnitNoUnit-8]
}

const _QuantityUnit_name = "mlcllmggkgcccs"

var _QuantityUnit_index = [...]uint8{0, 2, 4, 5, 7, 8, 10, 12, 14, 14}

func (i QuantityUnit) String() string {
	if i < 0 || i >= QuantityUnit(len(_QuantityUnit_index)-1) {
		return "QuantityUnit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QuantityUnit_name[_QuantityUnit_index[i]:_QuantityUnit_index[i+1]]
}
