// Code generated by "stringer -type=ServingsType -linecomment"; DO NOT EDIT.

package recipe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServingsTypeGuests-0]
	_ = x[ServingsTypeUnits-1]
}

const _ServingsType_name = "personnesunités"

var _ServingsType_index = [...]uint8{0, 9, 16}

func (i ServingsType) String() string {
	if i < 0 || i >= ServingsType(len(_ServingsType_index)-1) {
		return "ServingsType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServingsType_name[_ServingsType_index[i]:_ServingsType_index[i+1]]
}
