// Code generated by "stringer -type=PageSection -linecomment"; DO NOT EDIT.

package html

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PageSectionIngredients-0]
	_ = x[PageSectionRecipes-1]
}

const _PageSection_name = "ingredientsrecipes"

var _PageSection_index = [...]uint8{0, 11, 18}

func (i PageSection) String() string {
	if i < 0 || i >= PageSection(len(_PageSection_index)-1) {
		return "PageSection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PageSection_name[_PageSection_index[i]:_PageSection_index[i+1]]
}
